version: 2.1
orbs:
  pus: navikt/pus-orb@0.0.17

workflows:
  version: 2
  commit:
    jobs:
      - pus/test-frontend:
          context: pus
          filters:
            branches:
              ignore: master
      - pus/deploy-frontend:
          context: pus
          cluster: dev-fss
          filters:
            branches:
              only: master
      - prodsett:
          requires:
            - pus/deploy-frontend
          type: approval
          filters:
            branches:
              only: master
      - pus/deploy-latest:
          requires:
            - prodsett
          context: pus
          cluster: prod-fss
          filepath: ./nais.yaml
          filters:
            branches:
              only: master
