version: 2.1
orbs:
  pus: navikt/pus-orb@0.0.33

workflows:
  version: 2
  commit:
    jobs:
      - pus/test-frontend:
          context: pus
          filters:
            branches:
              ignore:
                - master
                - dev
      - pus/bygg-og-deploy-frontend:
          context: pus
          cluster: dev-fss
          filepath: ./nais-q.yaml
          filters:
            branches:
              only: dev
      - pus/bygg-og-deploy-backend:
          context: pus
          cluster: prod-fss
          filepath: ./nais.yaml
          filters:
            branches:
              only: master
